//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DinamikBlogSite.Models.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class BlogSiteDBEntities1 : DbContext
    {
        public BlogSiteDBEntities1()
            : base("name=BlogSiteDBEntities1")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<TBLADMİN> TBLADMİN { get; set; }
        public virtual DbSet<TBLCARDS> TBLCARDS { get; set; }
        public virtual DbSet<TBLGİRİS> TBLGİRİS { get; set; }
        public virtual DbSet<TBLHAKKİMDA> TBLHAKKİMDA { get; set; }
    }
}
