//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DinamikBlogSite.Models.Entity
{
    using System;
    using System.Collections.Generic;
    
    public partial class TBLCARDS
    {
        public int CardID { get; set; }
        public string CardBaslik { get; set; }
        public string CardAciklama { get; set; }
        public string cardButon { get; set; }
    }
}
